/*
SQLyog Enterprise - MySQL GUI v8.14 
MySQL - 5.7.6-m16-log : Database - jobportal
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`jobportal` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `jobportal`;

/*Table structure for table `userprofile` */

DROP TABLE IF EXISTS `userprofile`;

CREATE TABLE `userprofile` (
  `USERID` int(11) NOT NULL AUTO_INCREMENT,
  `ADDRESS` varchar(255) DEFAULT NULL,
  `FIRSTNAME` varchar(255) DEFAULT NULL,
  `LASTNAME` varchar(255) DEFAULT NULL,
  `REGISTRATION_ID` int(11) DEFAULT NULL,
  `ZIP` varchar(255) DEFAULT NULL,
  `INDUSTRY` varchar(255) DEFAULT NULL,
  `CURRENT_LOCATION` varchar(255) DEFAULT NULL,
  `DATE_OF_BIRTH` varchar(255) DEFAULT NULL,
  `GENDER` varchar(255) DEFAULT NULL,
  `PREFFERED_LOCATION` varchar(255) DEFAULT NULL,
  `RESUME_TITLE` varchar(255) DEFAULT NULL,
  `ROLE` varchar(255) DEFAULT NULL,
  `SALARY` varchar(255) DEFAULT NULL,
  `EXPERIENCE` varchar(255) DEFAULT NULL,
  `MARITAL_STATUS` varchar(255) DEFAULT NULL,
  `PHONE` varchar(255) DEFAULT NULL,
  `MAX_EXPERIENCE_ID` int(11) DEFAULT NULL,
  `MAX_SALARY_ID` int(11) DEFAULT NULL,
  `MIN_EXPERIENCE_ID` int(11) DEFAULT NULL,
  `MIN_SALARY_ID` int(11) DEFAULT NULL,
  `PREFERRED_CITY_ID` int(11) DEFAULT NULL,
  `CURRENT_CITY_ID` int(11) DEFAULT NULL,
  `HOME_CITY_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`USERID`),
  KEY `FK_j3l0eat83i2g73fu3y2f27fki` (`REGISTRATION_ID`),
  KEY `FK7857D37E4D61E039` (`MAX_SALARY_ID`),
  KEY `FK7857D37EBA000FA7` (`MIN_SALARY_ID`),
  KEY `FK7857D37E7A2C4B9` (`MAX_EXPERIENCE_ID`),
  KEY `FK7857D37E5630C774` (`REGISTRATION_ID`),
  KEY `FK7857D37E919F8D27` (`MIN_EXPERIENCE_ID`),
  KEY `FK7857D37E59CAAC34` (`PREFERRED_CITY_ID`),
  KEY `FK7857D37E35E94E76` (`PREFERRED_CITY_ID`),
  KEY `FK7857D37E68D1876E` (`CURRENT_CITY_ID`),
  KEY `FK7857D37E17F3F8D4` (`HOME_CITY_ID`),
  CONSTRAINT `FK7857D37E17F3F8D4` FOREIGN KEY (`HOME_CITY_ID`) REFERENCES `city` (`CITY_ID`),
  CONSTRAINT `FK7857D37E35E94E76` FOREIGN KEY (`PREFERRED_CITY_ID`) REFERENCES `city` (`CITY_ID`),
  CONSTRAINT `FK7857D37E4D61E039` FOREIGN KEY (`MAX_SALARY_ID`) REFERENCES `salary` (`SALARY_ID`),
  CONSTRAINT `FK7857D37E5630C774` FOREIGN KEY (`REGISTRATION_ID`) REFERENCES `login` (`REGISTRATION_ID`),
  CONSTRAINT `FK7857D37E68D1876E` FOREIGN KEY (`CURRENT_CITY_ID`) REFERENCES `city` (`CITY_ID`),
  CONSTRAINT `FK7857D37E7A2C4B9` FOREIGN KEY (`MAX_EXPERIENCE_ID`) REFERENCES `experience` (`EXPERIENCE_ID`),
  CONSTRAINT `FK7857D37E919F8D27` FOREIGN KEY (`MIN_EXPERIENCE_ID`) REFERENCES `experience` (`EXPERIENCE_ID`),
  CONSTRAINT `FK7857D37EBA000FA7` FOREIGN KEY (`MIN_SALARY_ID`) REFERENCES `salary` (`SALARY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

/*Data for the table `userprofile` */

insert  into `userprofile`(`USERID`,`ADDRESS`,`FIRSTNAME`,`LASTNAME`,`REGISTRATION_ID`,`ZIP`,`INDUSTRY`,`CURRENT_LOCATION`,`DATE_OF_BIRTH`,`GENDER`,`PREFFERED_LOCATION`,`RESUME_TITLE`,`ROLE`,`SALARY`,`EXPERIENCE`,`MARITAL_STATUS`,`PHONE`,`MAX_EXPERIENCE_ID`,`MAX_SALARY_ID`,`MIN_EXPERIENCE_ID`,`MIN_SALARY_ID`,`PREFERRED_CITY_ID`,`CURRENT_CITY_ID`,`HOME_CITY_ID`) values (5,'sdf',NULL,NULL,3,'458775',NULL,NULL,'09/22/2015','Female','ujjain','mayank','null','10000','2year','married','325345',8,8,7,7,323,187,692);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
